### ISSUE TITLE
"Could not find 'zip' in path, please configure and run again"

### ISSUE THREAD

**Issue by simon-heinen** [testfairy/testfairy-gradle-plugin#10]
I can't find any infos how to fix the following error:

Caused by: org.gradle.api.GradleException: Could not find 'zip' in path, please configure and run again
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
    at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:54)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
    at com.testfairy.plugins.gradle.TestFairyPlugin.locateZip(TestFairyPlugin.groovy:60)

**Comment by sirvon** [comment]
Simple solution hinted towards but unmentioned.

just install zip....
if your own debian/ubuntu...

```shell
apt-get install zip
```
